name = "sericaway"
main = ".open-next/worker.js"
compatibility_date = "2026-07-17"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }
account_id = "5daf5b5d4675b6b801bd579783d9c3c5"

[[d1_databases]]
binding = "DB"
database_name = "sericaway-db"
database_id = "e6293d1c-ebc6-4551-91fe-4d4b75425038"
